obj-$(CONFIG_NUBIA_SENSORS_FP)                  += gf318m/
obj-$(CONFIG_NUBIA_SENSORS_FP)                  += fpc1020/
obj-$(CONFIG_NUBIA_FP_AUTODETECT)		+= fp_autodetect.o
#---------------------------PROX SENSOR---------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_PROX_PA224)			+= txc_pa224.o
obj-$(CONFIG_NUBIA_SENSORS_PROX_TMD2772)		+= tmd2772.o
#---------------------------RGB SENSOR----------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_RGB_BH1745)			+= rohm_bh1745.o
#---------------------------PRESSURE_DEVICE ----------------------------#
obj-$(CONFIG_NUBIA_SENSORS_PRESSURE_DEVICE)		+= pressure_device_ndt.o
